    mov eax, 0
    mov ebx, 0
    mov ecx, 0
    mov edx, 0
    mov    eax, 0xdeadbeef
    bswap  eax
    mov    edx, eax
    and    eax, 0xf0f0f0f
    and    edx, 0xf0f0f0f0
    shr    edx, 0x4
    shl    eax, 0x4
    or     eax, edx
    mov    edx, eax
    and    eax, 0x33333333
    and    edx, 0xcccccccc
    shr    edx, 0x2
    shl    eax, 0x2
    or     eax, edx
    mov    edx, eax
    and    eax, 0x55555555
    and    edx, 0xaaaaaaaa
    add    eax, eax
    shr    edx, 1
    or     eax, edx